name: remove

on:
  push:
    branches:
      - main

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 5

  del_Release:
    runs-on: ubuntu-latest
    steps:
      - name: delete-release-action
        uses: sgpublic/delete-release-action@master
        with:
          release-drop: true
          release-keep-count: 7
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}